const NAME_SPACE = 'shipwell/address';

export const GET_ADDRESS_REQUEST = `${NAME_SPACE}/GET_ADDRESS_REQUEST`;
export const GET_ADDRESS_SUCCESS = `${NAME_SPACE}/GET_ADDRESS_SUCCESS`;
export const GET_ADDRESS_ERROR = `${NAME_SPACE}/GET_ADDRESS_ERROR`;

export const EDIT_ADDRESS_REQUEST = `${NAME_SPACE}/EDIT_ADDRESS_REQUEST`;
export const EDIT_ADDRESS_SUCCESS = `${NAME_SPACE}/EDIT_ADDRESS_SUCCESS`;
export const EDIT_ADDRESS_ERROR = `${NAME_SPACE}/EDIT_ADDRESS_ERROR`;

export const COMPLETE_ADDRESS = `${NAME_SPACE}/COMPLETE_ADDRESS`;
export const DELETE_ADDRESS = `${NAME_SPACE}/DELETE_ADDRESS`;

export default {
  GET_ADDRESS_REQUEST,
  GET_ADDRESS_SUCCESS,
  GET_ADDRESS_ERROR,
  EDIT_ADDRESS_REQUEST,
  EDIT_ADDRESS_SUCCESS,
  EDIT_ADDRESS_ERROR,
  COMPLETE_ADDRESS,
  DELETE_ADDRESS,
};
